using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using At.Syntax;
using Microsoft.CodeAnalysis;

namespace At
{
/// <summary>E.g., error or warning</summary>
public class AtDiagnostic 
{
    internal AtDiagnostic(string diagnosticId,AtSyntaxNode node,string message)
    {
        this.Id = diagnosticId;
        this.Location = node?.Position ?? -1;
        this.Message = message;
        this.Node = node;
    }

    /// <summary>Gets the diagnostic identifier. For diagnostics generated by the 
    /// compiler, this will be a numeric code with a prefix such as "AT1001".</summary>
    public virtual string Id {get;}
    public virtual int Location {get;}
    public virtual string Message {get;}
    public virtual AtSyntaxNode Node {get;}

    public static AtDiagnostic Create(string diagnosticId,AtSyntaxNode node, string message)
    {
        return new AtDiagnostic(diagnosticId,node,message);
    }
}

public class MsDiagnostic : AtDiagnostic
{
    public MsDiagnostic(Microsoft.CodeAnalysis.Diagnostic d) : base(d.Id,null,d.GetMessage())
    {
        Diagnostic = d;
    }

    public Diagnostic Diagnostic {get;}
}
}
