using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using At.Syntax;

namespace At
{
/// <summary>E.g., error or warning</summary>
public class AtDiagnostic 
{
    internal AtDiagnostic(string diagnosticId,AtToken token,string message)
    {
        this.Id = diagnosticId;
        this.Location = token.Position;
        this.Message = message;
    }

    /// <summary>Gets the diagnostic identifier. For diagnostics generated by the 
    /// compiler, this will be a numeric code with a prefix such as "AT1001".</summary>
    public virtual string Id
    {
	    get;
    }

    public virtual int Location
    {
        get;
    }
    
    public virtual string Message
    {
        get;
    }



    internal static AtDiagnostic Create(object expressionCluster,string v1,string v2,object error,int v3,bool v4)
    {
        throw new NotImplementedException();
    }
}
}
